### ISSUE TITLE
openssl cmdline tool compatible 

### ISSUE THREAD

**Issue by denisdemais** [dhuertas/AES#1]
Hi.

is possible decrypt the generate files using openssl cmdline tool ?

**Comment by dhuertas** [comment]
Short answer is no.

There is no mode of operation implemented here. With this code you're "stuck" ciphering/deciphering blocks of 128 bits, one at a time... unless the code of a mode of operation is provided.

You can find more info about modes of operation here: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation

UPDATE: number of bits per block, grammar.

**Comment by denisdemais** [comment]
thanks!

**Comment by dhuertas** [comment]
No further action needed ... closing issue ;)
