### ISSUE TITLE
MODE OF AES

### ISSUE THREAD

**Issue by DHONI123456** [dhuertas/AES#11]
I WAS LOOKING FOR A CODE TO PERFORM AES ENCRYPTION IN C. I CAME ACROSS A DOCUMENT STATING THAT THERE ARE DIFFERENT MODES OF AES (for eg:CBC,ECB). PLEASE TELL ME WHICH MODE OF AES IS BEING IMPLEMENTED THROUGH THIS CODE? IF I RUN THIS CODE IN A MICROCONTROLLER FOR MY PROJECT, WHICH RUNS AT 168Mhz CLOCK, HOW MUCH TIME WILL THE AES ENCRYPTION PART ALONE WILL TAKE TO COMPLETE THE PROCESS. LOOKING FORWARD FOR YOUR REPLY.
THANKS & REGARDS

**Comment by emorys** [comment]
您的邮件已收到,我将尽快回复，谢谢

**Comment by DHONI123456** [comment]
ThankYou sir

**Comment by dhuertas** [comment]
This project only contains code for the AES block cipher. Check out the Wikipedia article on block cipher modes of operation to learn more: [https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation)
