### ISSUE TITLE
Question about encrypt file?

### ISSUE THREAD

**Issue by LCUbtuntuCe** [dhuertas/AES#13]
How to encrypt a file, if the number of its size is not an integer multiple of 16?

**Comment by dhuertas** [comment]
Hi,

This project only contains code for the AES block cipher. Check out the wikipedia article on block cipher modes of operation to learn more: [https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation).

These modes of operation allow to encrypt/decrypt any amount of data using fixed-length block ciphers, such as files or streams.
