### ISSUE TITLE
licence?

### ISSUE THREAD

**Issue by nieknooijens** [dhuertas/AES#5]
Hi there

What is the licence of this project? MIT? GPL? LGPL? BSD?

Niek

**Comment by dhuertas** [comment]
Hi Niek,

Good question. I haven't thought of it yet. I think Github offers a handful of options? I'll check and pick the one that fits best. However, I wouldn't encourage using this implementation in any serious project anyway.

**Comment by nieknooijens** [comment]
then a MIT licence would be perfect. that's a licence for code examples.

**Comment by dhuertas** [comment]
Yes, MIT license seems like the right choice.

Thanks.
