### ISSUE TITLE
关于gmult.c

### ISSUE THREAD

**Issue by penghongquan** [dhuertas/AES#6]
你好，多谢你的代码，很久之前就在用你的AES源码，刚刚看到gmult.c这个文件，我不清楚是来干嘛的，我是小白，请问这个有什么作用，以前我记得是没有的，谢谢。

**Comment by dhuertas** [comment]
(I used translate.google.com to translate your question).

Ni hao,

It's an expansion of the `uint8_t gmult(uint8_t a, uint8_t b)` function into an array (a look up table). This reduces the number of instructions the compiler produces at the expense of increasing the size of the program. This results in a speed improvement of the algorithm execution.
